FROM node:16-alpine3.16 as build

WORKDIR /app

COPY package*.json ./

RUN npm install --quiet

COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY src ./src

RUN npm run build

RUN npm ci --only=production && npm cache clean --force

FROM node:16-alpine3.16 as production

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist

EXPOSE 3000

CMD [ "node", "dist/main.js" ]