version: '3.3'
services:
  quiz-db:
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - $DB_PORT:5432
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/pgsql
  quiz-api:
    container_name: quiz-api
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    env_file: .env
    environment:
      - PORT=$PORT
    expose:
      - $PORT
    ports:
      - $PORT:$PORT
    volumes:
      - ./src:/home/node/dev/quiz-api/src
      - ./tsconfig.json:/home/node/dev/quiz-api/tsconfig.json
    command: npm run start:dev
    depends_on: 
      - quiz-db

# Names our volume
volumes:
  my-db: